name: nordic_id
description: A Flutter plugin for Nordic ID Reader.
version: 1.0.0
homepage: "https://github.com/amorenew/nordic_id"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nordic_id.reader.nordic_id
        pluginClass: NordicIdPlugin
